apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webapp
spec:
  host: webapp-deployment-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-gateway-rule
  namespace: default
spec:
  hosts:
  - webapp-deployment-svc.default.svc.cluster.local
  - gke.prod.bh7cw.me
  - gke.prod.xinyuzhang.me
  gateways:
  - istio-system/webapp-gateway
  http:
  - match:
    - headers:
        foo:
          exact: bar
    route:
    - destination:
        host: webapp-deployment-svc
        port:
          number: 80
        subset: v1
  - route:
    - destination:
        host: webapp-deployment-svc
        port:
          number: 80
        subset: v2