apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch-master-rule
  namespace: default
spec:
  hosts:
  - jaeger-collector.istio-system.svc.cluster.local
  http:
  - match:  # notifier-webapp -> elasticsearch fails 100% of the time, status 400
    - sourceLabels:
        app: notifier-webapp-deployment
    fault:
      abort:
        percentage:
            value: 1
        httpStatus: 400
    route:
    - destination:
        host: elasticsearch-master
        port:
          number: 9200
        subset: v1
  - route:  # all other requests (processor-webapp) work normally
    - destination:
        host: elasticsearch-master
        port:
          number: 9200
        subset: v1