apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  labels:
    version: v2
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
      - name: docker-hub
      containers:
      - image: bboysticker/webapp:v2
        name: webapp
        envFrom:
        - configMapRef:
            name: webapp-db-config
        - secretRef: 
            name: webapp-db-secret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/helloworld
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 256Mi
            cpu: 500m